name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore LinuxSolution.sln
    - name: Build
      run: dotnet build LinuxSolution.sln --no-restore
    - name: Test
      run: dotnet test LinuxSolution.sln --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish Barotrauma/BarotraumaServer/WindowsServer.csproj -c Release -clp:"ErrorsOnly;Summary" --self-contained -r win-x64 \/p:Platform="x64"
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'linux_release.zip'
        #exclusions: '*.git* /*node_modules/* .editorconfig'
        path: 'Barotrauma/bin/ReleaseWindows/netcoreapp3.1/win-x64/publish'
        
    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            linux_release.zip
